version: '3.11'

services:
  app:
    build: .
    container_name: python-app
    environment:
      - MY_ENV_VAR=${MY_ENV_VAR}
    ports:
      - "5000:5000"
    user: "myuser"
    volumes:
      - ./app:/app
    restart: unless-stopped
    env_file:
      - .env

