FROM python:3.11-alpine AS system

RUN apk add --no-cache gcc musl-dev libffi-dev

WORKDIR /app

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ .

FROM python:3.11-alpine AS build

RUN adduser -D myuser

WORKDIR /app

COPY --from=system /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages

COPY app/ .

RUN chown -R myuser:myuser /app

USER myuser

CMD ["python", "main.py"]
