version: '3.11'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: my_python_app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app
    working_dir: /app
    env_file:
      - .env
    command: ["python", "main.py"]
